#!/usr/bin/env python3
"""
Build the installable "HamShackTech CW Trainer" app (static/cw-trainer/).

The app is a Progressive Web App (PWA): a small shell page with two tabs,
each showing one of the existing web trainers. Milestone 1 keeps the two
trainers essentially unchanged, so instead of hand-maintaining a second copy
of each, this script COPIES them from their web versions and applies a few
app-specific tweaks:

  * Google Fonts links  -> a local fonts.css (so the app works offline)
  * /apple-touch-icon.png -> ../icons/apple-touch-icon.png (inside the app folder)
  * the "home" button is hidden (inside the app it would navigate the tab
    away to the blog, which makes no sense in an installed app)

It also writes sw.js (the service worker) with the full list of files to
cache for offline use, and a cache version that is a hash of every file.
That means any change to any app file automatically produces a new version,
so installed copies update themselves -- nobody has to remember to bump it.

Run from the repo root after changing either trainer or the app shell:

    python3 scripts/build-cw-trainer.py --fonts /path/to/fontsource-packages

Hugo/Cloudflare do NOT run this script; its output in static/cw-trainer/ is
committed like any other static file. (Milestone 2 will replace the copied
trainers with shared code, at which point the copying goes away.)
"""
import argparse
import hashlib
import pathlib
import re
import shutil

ROOT = pathlib.Path(__file__).resolve().parent.parent
STATIC = ROOT / "static"
APP = STATIC / "cw-trainer"

# Which web trainer feeds which tab folder inside the app.
TRAINERS = {
    "icr": STATIC / "cw-tools" / "icr-trainer" / "index.html",
    "code-groups": STATIC / "cw-tools" / "code-groups-trainer" / "index.html",
}

# Font files the two trainers use: (family name, fontsource package, weights).
# Only the "latin" subset is bundled -- it covers everything the trainers
# display and keeps the download small (~20 KB per weight).
FONTS = [
    ("Oswald", "oswald", [400, 500, 600, 700]),
    ("Inter", "inter", [400, 500, 600]),
    ("JetBrains Mono", "jetbrains-mono", [400, 500, 700]),
    ("IBM Plex Sans", "ibm-plex-sans", [400, 500, 600]),
    ("IBM Plex Mono", "ibm-plex-mono", [400, 500, 600, 700]),
]

GENERATED_NOTE = (
    "<!-- GENERATED by scripts/build-cw-trainer.py from {src} -- do not edit "
    "this copy; edit the web trainer and re-run the script. -->\n"
)

# CSS injected into each trainer copy. Hides the home button (see above).
APP_CSS = "<style>/* CW Trainer app */ .home-link{display:none !important}</style>\n"


def replace_once(text, pattern, repl, label):
    """Regex replace that must match exactly once -- fails loudly otherwise,
    so an upstream edit to a trainer can't silently break the app copy."""
    new, n = re.subn(pattern, repl, text, flags=re.S)
    if n != 1:
        raise SystemExit(f"{label}: expected 1 match, found {n}")
    return new


def build_trainer(slug, src):
    html = src.read_text(encoding="utf-8")
    # The three <link> lines (2 preconnects + stylesheet) that load Google Fonts.
    html = replace_once(
        html,
        r'<link rel="preconnect" href="https://fonts\.googleapis\.com">\s*'
        r'<link rel="preconnect" href="https://fonts\.gstatic\.com" crossorigin>\s*'
        r'<link href="https://fonts\.googleapis\.com/css2\?[^"]*" rel="stylesheet">',
        '<link rel="stylesheet" href="../fonts/fonts.css">',
        f"{slug} fonts",
    )
    html = replace_once(html, r'src="/apple-touch-icon\.png"',
                        'src="../icons/apple-touch-icon.png"', f"{slug} mascot")
    html = replace_once(html, r"</head>", APP_CSS + "</head>", f"{slug} head")
    rel = src.relative_to(ROOT).as_posix()
    html = replace_once(html, r"^<!DOCTYPE html>\n",
                        "<!DOCTYPE html>\n" + GENERATED_NOTE.format(src=rel),
                        f"{slug} doctype")
    out = APP / slug / "index.html"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")


def build_fonts(fontsource_dir):
    font_dir = APP / "fonts"
    font_dir.mkdir(parents=True, exist_ok=True)
    css = ["/* Bundled copies of the trainers' Google Fonts, for offline use.\n"
           "   All five families are SIL Open Font License 1.1 -- see OFL.txt. */\n"]
    for family, pkg, weights in FONTS:
        # e.g. .../fontsource-oswald-5.3.0/package/files/oswald-latin-400-normal.woff2
        files_dir = next(fontsource_dir.glob(f"fontsource-{pkg}-*/package/files"))
        for w in weights:
            name = f"{pkg}-latin-{w}-normal.woff2"
            shutil.copyfile(files_dir / name, font_dir / name)
            css.append(
                "@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                "font-display:swap;src:url(%s) format('woff2')}\n" % (family, w, name))
    (font_dir / "fonts.css").write_text("".join(css), encoding="utf-8")
    lic = next(fontsource_dir.glob("fontsource-oswald-*/package/LICENSE"))
    shutil.copyfile(lic, font_dir / "OFL.txt")


def build_icons():
    icon_dir = APP / "icons"
    icon_dir.mkdir(parents=True, exist_ok=True)
    for name in ("apple-touch-icon.png", "android-chrome-192x192.png",
                 "android-chrome-512x512.png", "favicon-32x32.png"):
        shutil.copyfile(STATIC / name, icon_dir / name)


def build_service_worker():
    # Every file the app needs, as the URL the browser will request.
    # Folder pages are listed by folder URL ("/cw-trainer/icr/"), which is how
    # Cloudflare Pages serves them (it redirects ".../index.html" to "/").
    files = sorted(p for p in APP.rglob("*")
                   if p.is_file() and p.name not in ("sw.js", "OFL.txt"))
    urls, digest = [], hashlib.sha256()
    for p in files:
        rel = p.relative_to(STATIC).as_posix()
        url = "/" + (rel[: -len("index.html")] if rel.endswith("index.html") else rel)
        urls.append(url)
        digest.update(rel.encode() + b"\0" + p.read_bytes())
    template = (APP.parent.parent / "scripts" / "cw-trainer-sw.template.js").read_text()
    sw = template.replace("__VERSION__", digest.hexdigest()[:12])
    sw = sw.replace("__PRECACHE__", ",\n  ".join(f"'{u}'" for u in urls))
    (APP / "sw.js").write_text(sw, encoding="utf-8")
    print(f"sw.js: {len(urls)} files, version {digest.hexdigest()[:12]}")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts", help="folder holding extracted @fontsource packages "
                    "(only needed when the font list changes)")
    args = ap.parse_args()
    for slug, src in TRAINERS.items():
        build_trainer(slug, src)
    if args.fonts:
        build_fonts(pathlib.Path(args.fonts))
    build_icons()
    build_service_worker()
